### ISSUE TITLE
Unexpected end of JSON input running scan step 3

### ISSUE THREAD

**Issue by dkilcy-scality** [scality/s3utils#245]
While running thru Scan Step 3 on a raft follower in the Allstate lab, I encountered the below.
The problem is reproduceable.

```
{"name":"s3utils:CompareRaftMembers:followerDiff","time":1658440116134,"dbPath":"/databases/e74878182032031870d240fb19257886/7/0/storeDb30","level":"info","message":"starting scan of database","hostname":"nb-storage-02","pid":1}
{"name":"s3utils:CompareRaftMembers:followerDiff","time":1658440116137,"dbPath":"/databases/e74878182032031870d240fb19257886/7/0/storeDb30","level":"info","message":"completed scan of database","hostname":"nb-storage-02","pid":1}
{"name":"s3utils:CompareRaftMembers:followerDiff","time":1658440116137,"dbPath":"/databases/e74878182032031870d240fb19257886/7/0/storeDb31","level":"info","message":"starting scan of database","hostname":"nb-storage-02","pid":1}
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at DBListStream._transform (/usr/src/app/CompareRaftMembers/DBListStream.js:66:25)
    at DBListStream.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at DBListStream.Writable.write (node:internal/streams/writable:334:10)
    at ReadStream.ondata (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at ReadStream.emit (node:events:527:28)
    at ReadStream.emit (node:domain:475:12)
    at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12)
[root@nb-storage-02 tmp]# 
```

**Comment by dkilcy-scality** [comment]
user error

**Comment by dkilcy-scality** [comment]
Reopening.  I thought I made a mistake on the scan step 3, but I did not.     Version is 1.12.2

**Comment by dkilcy-scality** [comment]
Found the issue, it was something else
